name: Check AIEngineerPack for New Volumes

on:
  schedule:
    # Run twice daily at 8:00 AM and 8:00 PM Eastern Time (ET)
    # ET is UTC-4 (summer) or UTC-5 (winter)
    # 12:00 and 00:00 UTC should be 8:00 AM and 8:00 PM ET respectively
    - cron: '0 12,0 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  check-volumes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run volume check
        env:
          # Email configuration (optional)
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          # Discord configuration (optional)
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Telegram configuration (optional)
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_aiengineerpack.py
        
      - name: Commit and push if volumes changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add volumes_found.txt || true
          git commit -m "Update tracked volumes" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }} || echo "Failed to push changes" 