name: Check Website for New Volumes

on:
  schedule:
    # Run at 8:00 AM and 8:00 PM UTC (which is approximately 4:00 AM/PM EDT)
    - cron: '0 8,20 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  check_website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run volume check
      env:
        # Email configuration
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        
        # Discord configuration
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        
        # Telegram configuration
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python check_aiengineerpack.py
      
    - name: Commit volumes file if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add volumes_found.txt telegram_subscribers.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update volumes and subscribers detected on website"
        git push 