name: Check AIEngineerPack Website

on:
  schedule:
    # Run twice daily (at 8:00 and 20:00 UTC)
    - cron: '0 8,20 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run website check
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        run: python check_aiengineerpack.py
        
      - name: Commit and push if hash changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add previous_hash.txt || true
          git commit -m "Update website hash" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }} || echo "Failed to push changes" 